In [1]:
import pandas as pd
import numpy as np

In [2]:
data = np.random.rand(4, 4)

In [5]:
df = pd.DataFrame(data)
df

          0         1         2         3
0  0.805353  0.013253  0.756060  0.722686
1  0.565915  0.292495  0.223339  0.197996
2  0.333429  0.928524  0.395773  0.308315
3  0.617398  0.163708  0.964692  0.306421

In [6]:
df.columns=['Random value 1', 'Random value 2', 'Random value 3', 'Random value 4']
df

   Random value 1  Random value 2  Random value 3  Random value 4
0        0.805353        0.013253        0.756060        0.722686
1        0.565915        0.292495        0.223339        0.197996
2        0.333429        0.928524        0.395773        0.308315
3        0.617398        0.163708        0.964692        0.306421

In [7]:
df.describe()

       Random value 1  Random value 2  Random value 3  Random value 4
count        4.000000        4.000000        4.000000        4.000000
mean         0.580524        0.349495        0.584966        0.383854
std          0.194231        0.402533        0.336667        0.231698
min          0.333429        0.013253        0.223339        0.197996
25%          0.507794        0.126094        0.352665        0.279315
50%          0.591657        0.228101        0.575917        0.307368
75%          0.664387        0.451502        0.808218        0.411908
max          0.805353        0.928524        0.964692        0.722686

In [8]:
df.isnull().sum()

Random value 1    0
Random value 2    0
Random value 3    0
Random value 4    0
dtype: int64

In [13]:
df['Random value 1'].dtype

dtype('float64')

In [14]:
df.loc[:, ['Random value 2', 'Random value 3']]

   Random value 2  Random value 3
0        0.013253        0.756060
1        0.292495        0.223339
2        0.928524        0.395773
3        0.163708        0.964692

In [15]:
df.iloc[:, [1, 2]]

   Random value 2  Random value 3
0        0.013253        0.756060
1        0.292495        0.223339
2        0.928524        0.395773
3        0.163708        0.964692